export const firstData = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'J e r e m y . T r i e u',
    headLine: 'Front-end Developer',
    description: ['I am a Front-end Developer who just recently graduated from San Jose State University with a Bachelor Degree in Computer Science. For the past 4 years in college, I learned a lot of intertesting programming topics, but my heart truly knows that UI/UX development is the career path that I want to focus on.'],
    buttonLabel: 'Get Started',
    imgStart: false,
    img: './jeremy.png',
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
    imgStart: false,
    buttonLink: '/',
    logoList:[],
    logoList2:[],
}

export const secondData = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'J e r e m y . T r i e u',
    headLine: 'My background',
    description: ['University: San Jose State University\.', 'Degree: Bachelor\'s in Computer Science.', 'Experience in programming: 4 years.', 'Programming skill: JavaScript(React.js), Java, Python(DJango), HTML + CSS(bootstrap, styled components), Jira, Linux(OS + Command + Bash), Version Control(GitHub, GitLab, BitBucket).'],
    buttonLabel: 'My Resume',
    imgStart: false,
    img: './jeremy2.svg',
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
    imgStart: true,
    buttonLink: 'https://docs.google.com/document/d/1T1iSUcpd8ibDVmPUYNS1HKvkcqeoV7jwKDAOlxUwPqE/edit',
    logoList:[],
    logoList2: [],
}

export const thirdData = {
    id: 'projects',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'J e r e m y . T r i e u',
    headLine: 'My projects',
    description: ['Jeremy The Frontfreak: My portfolio, which is built with React and Styled-components.', 'Instructour: A fullstack app using React+DJango + MySQL, which is a clone of Ratemyprofessor.', 'SimStation: using Java and MVC Models to build a desktop app to demonstrating the flying habits of different kinds of birds.'],
    buttonLabel: 'My GitHub',
    imgStart: false,
    img: './jeremy3.svg',
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
    imgStart: false,
    buttonLink: 'https://www.github.com/JeremyTrieu',
    logoList:[],
    logoList2: [],
}

export const fourthData = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'J e r e m y . T r i e u',
    headLine: 'Contact me',
    description: [],
    buttonLabel: 'Send me an email',
    imgStart: false,
    img: './jeremy4.svg',
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
    imgStart: true,
    buttonLink: '/email',
    logoList: ['./gmail_logo.png', './linkedin_logo.png', './ig_logo.png'],
    logoList2: [['./gmail_logo.png', 'jeremytrieu1612@gmail.com'], ['./linkedin_logo.png', 'https://www.linkedin.com/in/jeremy-trieu/'], ['./ig_logo.png', 'https://www.instagram.com/jeremytrieu/']],
}